pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  build.version.major: 1
  build.version.minor: 0
  build.version.revision: $[counter(format('{0}.{1}', variables['build.version.major'], variables['build.version.minor']), 1000)]
  build.version: $(build.version.major).$(build.version.minor).$(build.version.revision).0
  build.versionShort: $(build.version.major).$(build.version.minor).$(build.version.revision)
  build.date: $[format('{0:yyyy}-{0:MM}-{0:dd}T{0:HH}:{0:mm}:{0:ss}', pipeline.startTime)]

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    publishWebProjects: false
    arguments: '-c $(buildConfiguration) -p:Version=$(build.version)'
    projects: '**/*.csproj'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: 'pack'

- task: DotNetCoreCLI@2
  displayName: dotnet push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '91a552bc-359d-4f28-bdbd-f36f71cfdf81'
